<?php

namespace ContainerMhMbyVS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2p9CSkIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2p9CSkI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2p9CSkI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', '.errored.v0hC7bm', NULL, 'Cannot determine controller argument for "App\\Controller\\BeautybaeController::avis()": the $repo argument is type-hinted with the non-existent class or interface: "App\\Controller\\AvisRepository". Did you forget to add a use statement?'],
        ], [
            'repo' => '?',
        ]);
    }
}
