<?php

namespace ContainerMhMbyVS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_V0hC7bmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.v0hC7bm' shared service.
     *
     * @return \App\Controller\AvisRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\BeautybaeController::avis()": the $repo argument is type-hinted with the non-existent class or interface: "App\\Controller\\AvisRepository". Did you forget to add a use statement?');
    }
}
