<?php

namespace ContainerMhMbyVS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A0hrWjVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A0hrWjV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A0hrWjV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['privates', '.errored.8LY66ZE', NULL, 'Cannot determine controller argument for "App\\Controller\\BeautybaeController::create()": the $manager argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
            'request' => ['privates', '.errored.B1z6FHW', NULL, 'Cannot determine controller argument for "App\\Controller\\BeautybaeController::create()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'manager' => '?',
            'request' => '?',
        ]);
    }
}
