<?php

namespace ContainerJcJLJEY;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SHuY9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._S_HuY9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._S_HuY9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BeautybaeController::avis' => ['privates', '.service_locator.uRm8g0q', 'get_ServiceLocator_URm8g0qService', true],
            'App\\Controller\\BeautybaeController::create' => ['privates', '.service_locator.47P5gN6', 'get_ServiceLocator_47P5gN6Service', true],
            'App\\Controller\\ContactController::contact' => ['privates', '.service_locator.cvnXks2', 'get_ServiceLocator_CvnXks2Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\BeautybaeController:avis' => ['privates', '.service_locator.uRm8g0q', 'get_ServiceLocator_URm8g0qService', true],
            'App\\Controller\\BeautybaeController:create' => ['privates', '.service_locator.47P5gN6', 'get_ServiceLocator_47P5gN6Service', true],
            'App\\Controller\\ContactController:contact' => ['privates', '.service_locator.cvnXks2', 'get_ServiceLocator_CvnXks2Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\BeautybaeController::avis' => '?',
            'App\\Controller\\BeautybaeController::create' => '?',
            'App\\Controller\\ContactController::contact' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BeautybaeController:avis' => '?',
            'App\\Controller\\BeautybaeController:create' => '?',
            'App\\Controller\\ContactController:contact' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
