<?php

namespace ContainerJcJLJEY;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_3hORTjzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.3hORTjz' shared service.
     *
     * @return \App\Controller\ObjectManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\BeautybaeController::create()": the $manager argument is type-hinted with the non-existent class or interface: "App\\Controller\\ObjectManager". Did you forget to add a use statement?');
    }
}
