<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY4CBuqr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY4CBuqr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY4CBuqr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY4CBuqr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY4CBuqr\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y4CBuqr',
    'container.build_id' => '954bd8fe',
    'container.build_time' => 1633697298,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY4CBuqr');
