<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPLWziIA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPLWziIA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPLWziIA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPLWziIA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPLWziIA\App_KernelDevDebugContainer([
    'container.build_hash' => 'PLWziIA',
    'container.build_id' => '2d78c138',
    'container.build_time' => 1634235146,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPLWziIA');
