<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'beautybae' => [[], ['_controller' => 'App\\Controller\\BeautybaeController::index'], [], [['text', '/beautybae']], [], []],
    'accueil' => [[], ['_controller' => 'App\\Controller\\BeautybaeController::accueil'], [], [['text', '/accueil']], [], []],
    'avis' => [[], ['_controller' => 'App\\Controller\\BeautybaeController::avis'], [], [['text', '/avis']], [], []],
    'avis_create' => [[], ['_controller' => 'App\\Controller\\BeautybaeController::create'], [], [['text', '/avis/new']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::contact'], [], [['text', '/contact']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
