<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'accueil' => [[], ['_controller' => 'App\\Controller\\BeautybaeController::accueil'], [], [['text', '/accueil']], [], []],
    'beautybae' => [[], ['_controller' => 'App\\Controller\\BeautybaeController::index'], [], [['text', '/beautybae']], [], []],
    'prestation' => [[], ['_controller' => 'App\\Controller\\PrestationController::index'], [], [['text', '/prestation']], [], []],
    'reserver' => [['id'], ['_controller' => 'App\\Controller\\PrestationController::reserver'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/prestation']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
